# Build the installer  ->  StudyCompanion-Setup.exe
# Usage: powershell -ExecutionPolicy Bypass -File build-setup.ps1
#
# The installer is a single self-contained exe: the main program, the schedule and
# the textbook index are embedded as resources, so there is nothing else to download.
#
# NOTE: keep this file ASCII-only (PowerShell 5.1 reads .ps1 as ANSI without a BOM).
$ErrorActionPreference = "Stop"

$here    = Split-Path -Parent $MyInvocation.MyCommand.Path
$appDir  = Join-Path (Split-Path -Parent $here) "StudyCompanion"
$csc     = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { $csc = "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe" }
if (-not (Test-Path $csc)) { throw "csc.exe not found" }

# ---- version comes from the app source, so installer and app can never drift apart
$gh = Get-Content (Join-Path $appDir "src\GitHub.cs") -Raw
if ($gh -match 'VersionTag\s*=\s*"v?([0-9][^"]*)"') { $ver = $Matches[1] }
else { throw "cannot parse VersionTag from GitHub.cs" }
Write-Host "version: $ver"

# ---- inputs must exist
$exe   = Join-Path $appDir "StudyCompanion.exe"
$sched = Join-Path (Split-Path -Parent $appDir) "Schedule.xlsx"
$books = Join-Path $appDir "data\books.tsv"
$pages = Join-Path $appDir "data\pages.tsv"
$ico   = Join-Path $appDir "assets\app.ico"
foreach ($p in @($exe, $sched, $books, $pages, $ico)) {
    if (-not (Test-Path $p)) { throw "missing input: $p" }
}

# ---- generate SetupInfo.cs
$out = Join-Path $here "build"
if (Test-Path $out) { Remove-Item -Recurse -Force $out }
New-Item -ItemType Directory -Force $out | Out-Null

$info = @"
// AUTO-GENERATED by build-setup.ps1 -- do not edit
namespace StudyCompanion.Setup
{
    public static class SetupInfo
    {
        public const string Version = "$ver";
    }
}
"@
Set-Content -Path (Join-Path $out "SetupInfo.cs") -Value $info -Encoding UTF8

# ---- compile
$srcs = @(Get-ChildItem (Join-Path $here "src") -Filter *.cs | ForEach-Object { $_.FullName })
$srcs += (Join-Path $out "SetupInfo.cs")

$target = Join-Path $here "StudyCompanion-Setup.exe"
if (Test-Path $target) { Remove-Item $target -Force }

& $csc /nologo /codepage:65001 /target:winexe /optimize+ /out:$target `
    /win32icon:$ico `
    "/resource:$exe,App.StudyCompanion.exe" `
    "/resource:$sched,App.Schedule.xlsx" `
    "/resource:$books,App.books.tsv" `
    "/resource:$pages,App.pages.tsv" `
    /r:System.dll /r:System.Drawing.dll /r:System.Windows.Forms.dll /r:System.Core.dll `
    $srcs

if ($LASTEXITCODE -ne 0) { throw "compile failed" }

$kb = [math]::Round((Get-Item $target).Length / 1KB, 1)
Write-Host "OK -> $target  ($kb KB)" -ForegroundColor Green
